services:
  connect:
    tty: true
    
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: connect

    volumes:
      - type: bind
        source: .
        target: /home/c-connect